[build]
  # Directorio donde están los archivos compilados
  publish = "dist/financello-front/browser"
  
  # Comando para construir la aplicación
  command = "npm run build"

[build.environment]
  # Versión de Node.js
  NODE_VERSION = "22"

# Configuración para SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers para mejorar seguridad y rendimiento
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Headers específicos para archivos estáticos
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Headers para archivos JS y CSS
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"
